# Generated by Django 4.2.7 on 2024-01-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание новости')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='map/objectImages/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название носоти')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание новости')),
            ],
        ),
    ]
