# Generated by Django 4.2.7 on 2024-01-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNCore', '0002_alter_events_options_alter_news_options_news_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя спикера')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография спикера')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/speakers/', verbose_name='Изображение спикера')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='VNCore.speaker', verbose_name='Спикеры'),
        ),
    ]
