# Generated by Django 4.2.7 on 2024-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNCore', '0004_organizers_alter_speaker_options_events_organizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizers',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organizers',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organizers',
            name='numberParticipants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizers',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография орагнизатора'),
        ),
        migrations.AlterField(
            model_name='organizers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя организатора'),
        ),
    ]
