# Generated by Django 4.2.7 on 2024-01-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNCore', '0005_organizers_category_organizers_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizers',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organizers',
            name='date',
        ),
        migrations.AddField(
            model_name='events',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
