# Generated by Django 4.2.7 on 2024-01-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNCore', '0006_remove_organizers_category_remove_organizers_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizers',
            name='numberParticipants',
        ),
        migrations.AddField(
            model_name='events',
            name='numberParticipants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
