# Generated by Django 4.2.7 on 2024-01-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VNCore', '0010_organizers_post_speaker_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
        migrations.AlterField(
            model_name='rating',
            name='alpha',
            field=models.IntegerField(verbose_name='Альфа'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='countEvents',
            field=models.IntegerField(verbose_name='Количество мероприятий'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fullname',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='omega',
            field=models.IntegerField(verbose_name='Омега'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='points',
            field=models.IntegerField(verbose_name='Баллы'),
        ),
    ]
